---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kbot-secrets
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: kbot-secrets
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  interval: 1m0s
  path: ./secrets
  prune: true
